security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        database_users:
            entity: { class: App\Entity\User, property: email }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: database_users

            oauth:
                resource_owners:
                    github: "/login/check-github"
                login_path: /login
                failure_path: /login
                default_target_path: /
                use_forward: false
                oauth_user_provider:
                    service: App\Security\OAuthUserService

            

            logout:
                path: /logout
                target: homepage
                enable_csrf: true


            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800

            entry_point: oauth

            login_throttling:
                max_attempts: 3

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_USER }
        - { path: ^/, roles: PUBLIC_ACCESS }

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10

        firewalls:
            main:
                http_basic: ~
