homepage:
    path: /{_locale}
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: default/homepage.html.twig
        _locale: '%app.locale%'

controllers:
    resource:
        path: '../src/Controller/'
        namespace: App\Controller
    type: attribute
    prefix: /{_locale}
    defaults:
        _locale: '%app.locale%'

_symfony_logout:
    resource: security.route_loader.logout
    type: service
login_check_github:
    path: /login/check-github
